stages:
- build
- docker
- deploy

build:
  stage: build
  tags:
    - maven
  script:
  - echo "Building..."
  - mvn $MAVEN_REMOTE_OPTS verify -DskipTests
  - echo "Building ended"
  artifacts:
    paths:
    - target/*.jar

docker:
  stage: docker
  tags:
  - docker
  dependencies:
    - build
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:20.10.23-dind
      alias: docker
      command: ["--insecure-registry", "192.168.252.88:5000"]

  script:
  - echo "Docker Image Build Start"
  - ls target
  - docker build -t 192.168.252.88:5000/os3/ubik/ubikservice:latest -f ./infra/Dockerfile .
  - echo "Docker Image Build End"
  - echo "Docker Image Push Start"
  - docker push 192.168.252.88:5000/os3/ubik/ubikservice:latest
  - echo "Docker Image Push End"

deploy:
  stage: docker
  tags:
  - docker
  needs:
    - docker
  variables:
    DOCKER_HOST: tcp://192.168.252.7:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:20.10.23-dind
      alias: docker
      command: ["--insecure-registry", "192.168.252.88:5000"]

  script:
  - echo "Deploy start"
  - docker run -e "SPRING_PROFILES_ACTIVE=testing" -e "LOG_LEVEL=DEBUG" 192.168.252.88:5000/os3/ubik/ubikservice:latest
  - echo "Deploy end" 
