default:
  image: maven:3.9.1-eclipse-temurin-20-alpine

stages:
- build
- test
- package
- docker

build:
  stage: build
  tags:
    - maven
  script:
  - echo "Building..."
  - mvn $MAVEN_REMOTE_OPTS clean install -DskipTests
  - echo "Building ended"
  artifacts:
    paths:
    - target

test:
  stage: test
  tags:
    - maven
  dependencies:
    - build
  artifacts:
    paths:
    - target
  script:
  - echo "Testing..."
  - mvn $MAVEN_REMOTE_OPTS test
  - echo "Testing ended"

package:
  stage: package
  tags:
    - maven
  dependencies:
    - test
  artifacts:
    paths:
    - target
  script:
  - echo "Packaging..."
  - mvn $MAVEN_REMOTE_OPTS package -DskipTests
  - echo "Packaging ended"

docker:
  stage: docker
  tags:
    -  maven
  dependencies:
    - package
  script:
  - echo "Packaging..."
  - mvn $MAVEN_REMOTE_OPTS spring-boot:build-image -DskipTests
  - echo "Packaging ended"   
