default:
  image: maven:3.9.1-eclipse-temurin-17-alpine

stages:
- build
- test
- package
- docker

build:
  stage: build
  tags:
    - maven
  script:
  - echo "Building..."
  - mvn $MAVEN_REMOTE_OPTS clean install -DskipTests
  - echo "Building ended"
  artifacts:
    paths:
    - target

test:
  stage: test
  tags:
    - maven
  dependencies:
    - build
  artifacts:
    paths:
    - target
  script:
  - echo "Testing..."
  - mvn $MAVEN_REMOTE_OPTS test
  - echo "Testing ended"

package:
  stage: package
  tags:
    - maven
  dependencies:
    - test
  artifacts:
    paths:
    - target
  script:
  - echo "Packaging..."
  - mvn $MAVEN_REMOTE_OPTS package -DskipTests
  - echo "Packaging ended"

docker:
  stage: docker
  tags:
  - maven
  dependencies:
  - package
  variables:
    DOCKER_HOST: tcp://192.168.252.88:2375
  script:
  - echo "Building start"
  - mvn $MAVEN_REMOTE_OPTS spring-boot:build-image -DskipTests -Ddocker.publishRegistry.url=192.168.252.88 -Ddocker.publishRegistry.username=$DOCKER_REGISTRY_USERNAME -Ddocker.publishRegistry.password=$DOCKER_REGISTRY_PASSWD -Dspring-boot.build-image.publish=true -Dspring-boot.build-image.imageName=192.168.252.88/library/ubikservice:v1
  - echo "Building end"   
