stages:
- build
- test
- package
- docker

build:
  stage: build
  tags:
    - maven
  script:
  - echo "Building..."
  - mvn $MAVEN_REMOTE_OPTS clean install -DskipTests
  - echo "Building ended"


test:
  stage: test
  tags:
    - maven
  dependencies:
    - build
  script:
  - echo "Testing..."
  - mvn $MAVEN_REMOTE_OPTS test
  - echo "Testing ended"

package:
  stage: package
  tags:
    - maven
  dependencies:
    - test
  artifacts:
    paths:
    - target/*.jar
  script:
  - echo "Packaging..."
  - mvn $MAVEN_REMOTE_OPTS package -DskipTests
  - echo "Packaging ended"

docker:
  stage: docker
  tags:
  - docker
  dependencies:
  - package
  variables:
    GIT_STRATEGY: none
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  services:
    - name: docker:20.10.23-dind
      alias: docker
      command: ["--insecure-registry = 192.168.252.88:5000"]

  script:
  - echo "Building start"
  - echo "${DOCKER_REGISTRY_PASSWD:?}" | docker login "192.168.252.88:5000" --password-stdin -u "${DOCKER_REGISTRY_USERNAME:?}" 
  - docker build -f infra/Dockerfile --tag=ubikservice:latest -t 192.168.252.88:5000/os3/ubikservice:latest
  - docker push ubikservice:latest
  - echo "Building end"   
