stages:
- build
- docker
- deploy

build:
  stage: build
  tags:
    - maven
  script:
  - echo "Building..."
  - mvn $MAVEN_REMOTE_OPTS verify -DskipTests
  - echo "POM_VERSION=$(mvn -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec -q)" > vars.env
  - echo "Building ended"
  artifacts:
    paths:
    - target/*.jar
    reports:
      dotenv: vars.env

docker:
  stage: docker
  tags:
  - docker
  dependencies:
    - build
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:20.10.23-dind
      alias: docker
      command: ["--insecure-registry", "192.168.252.88:5000"]

  script:
  - echo "Docker Image Build Start"
  - ls target
  - docker build -t 192.168.252.88:5000/os3/ubik/ubikservice:$POM_VERSION -f ./infra/Dockerfile .
  - echo "Docker Image Build End"
  - echo "Docker Image Push Start"
  - docker push 192.168.252.88:5000/os3/ubik/ubikservice::$POM_VERSION
  - echo "Docker Image Push End"

deploy:
  stage: docker
  tags:
  - docker
  needs:
    - docker
  variables:
    DOCKER_HOST: tcp://192.168.252.140:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:20.10.23-dind
      alias: docker
      command: ["--insecure-registry", "192.168.252.88:5000"]

  script:
  - echo "Deploy start"
  - docker rm -f ubik_service
  - docker run --name ubik_service -e "SPRING_PROFILES_ACTIVE=testing" -e "LOG_LEVEL=INFO" --restart unless-stopped -p 9080:8080 192.168.252.88:5000/os3/ubik/ubikservice:$POM_VERSION -d
  - echo "Deploy end" 
