stages:
- build
- docker

build:
  stage: build
  tags:
    - maven
  script:
  - echo "Building..."
  - mvn $MAVEN_REMOTE_OPTS verify -DskipTests
  - echo "Building ended"
  artifacts:
    paths:
    - target

docker:
  stage: docker
  tags:
  - docker
  variables:
    DOCKER_HOST: tcp://192.168.252.88:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  script:
  - echo "Building start"
  - ls .
  - docker build -t 192.168.252.88:5000/os3/ubikservice:latest ./infra
  - docker push ubikservice:latest
  - echo "Building end"   
