stages:
- build
- test
- docker

build:
  stage: build
  tags:
    - maven
  script:
  - echo "Building..."
  - mvn $MAVEN_REMOTE_OPTS clean install -DskipTests
  - echo "Building ended"
  artifacts:
    paths:
    - target/*.jar

test:
  stage: test
  tags:
    - maven
  dependencies:
    - build
  script:
  - echo "Testing..."
  - mvn $MAVEN_REMOTE_OPTS test
  - echo "Testing ended"

docker:
  stage: docker
  tags:
  - docker
  dependencies:
  - test
  variables:
    DOCKER_HOST: tcp://192.168.252.88:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  script:
  - echo "Building start"
  - docker build -f infra/Dockerfile --tag=ubikservice:latest
  - docker push ubikservice:latest
  - echo "Building end"   
