spring:
  neo4j:
    uri: bolt://localhost:7689
    authentication:
      username: neo4j
      password: neo4jtfg
logging:
  level:
    org.springframework.data.neo4j:DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
